### PR TITLE
Fix #127 : Update TEP status graphic to replace "Compound design and TEP validation" with "First-round progression for TEP validation"

### LINKED ISSUE #127: Update text in TEP overview graphic
From SAB discussion, we need to word-smith "Compound design and TEP validation". 

I suggestion "First-round progression for TEP validation"

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #127

### CODE REVIEW

**Comment by jchodera** [comment]
@phraenquex: Here's what this looks like now. OK to merge?
image

**Comment by phraenquex** [comment]
Ah, there's space to spare.  Then let's do:   

> _First-round
> fragment progression 
> for TEP validation_

**Comment by jchodera** [comment]
What, you couldn't come up with a whole Haiku? ;)
image

**Comment by phraenquex** [comment]
_Initial fragment
progression to validate
if target's enabled_

:P

**Comment by jchodera** [comment]
Lovely! I've at least merged the non-Haiku improvement until I can figure out how to control line breaks more finely.

**Pull request merged**
