### PR TITLE
Add a button on TEP page to download a csv with 'pre-TEP' information

### PR DESCRIPTION
**Pull request by JenkeScheen**
should be good to go. 

This adds a simple download button to the TEP page with the most current Scarab export:
image

@jchodera can you check whether you're happy with the naming of the button?

Clicking the button download a csv `scarab_export_ASAP.csv` that contains (at the moment) 9 rows with a bunch of data on protein purification protocols. This isn't enough data to build a full TEP yet, but serving this information in this way is a decent intermediate imo. 

Snapshot of csv:
image

... then there's ~10 more columns to the right with e.g. DNA sequence information, assay conditions, GenBank URLs. Some fields will be NaN.

### CODE REVIEW

**Review by jchodera — APPROVED** [review]
Good for now! Thanks!

**Comment by jchodera** [comment]
@JenkeScheen : It turns out this button appeared everywhere, even on pages it wasn't supposed to, so I have to delete it in #27

**Comment by JenkeScheen** [comment]
oh no! I'll get a PR in that works correctly.

**Comment by jchodera** [comment]
@JenkeScheen Let's not worry about it for now, since I think our conclusion was that the data isn't quite ready to easily be shared in a clear and interpretable manner.

**Comment by JenkeScheen** [comment]
ah yes, forgot about this one. Discussed this with @LizbeK as well, agreed.

**Pull request merged**
